# Site configuration

devNum: 28


# Jekyll configuration


url: https://xdag.top
baseurl: ""

#paginate: 7
#paginate_path: "/blog/page:num"

sass:
  style: compressed
#
#plugins:
##  - jekyll-paginate
#
### Exclude files from build folder
#exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'package.json', 'package-lock.json']

## SEO

title: XDAG
description: A new DAG-based cryptocurrency
logo: /assets/images/logo.png
default_image: /assets/images/default-card.png

author:
  name: Xdag.top
  twitter: XDAG_Community
  email: communitymanager@xdag.io 

      
## Translations

languages: ["zh", "en", "se", "es", "fr", "cs"]
exclude_from_localizations: ["assets", "blog", "CNAME", "README.md", "_posts"]