# Site configuration

devNum: 28
community_wallet: bFi6yqUCnDvP2hBSUcHCmfBgJB2Jew6f

# Jekyll configuration


url: xdag.top
baseurl: ""

#paginate: 7
#paginate_path: "/blog/page:num"

sass:
  style: compressed
#
#plugins:
##  - jekyll-paginate
#
### Exclude files from build folder
#exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'package.json', 'package-lock.json']

## SEO

title: XDAG
description: A new DAG-based cryptocurrency
logo: /assets/images/logo.png
default_image: /assets/images/default-card.png

author:
  name: Xdag.top
  twitter: XDAG_Community
  email: communitymanager@xdag.io 

